{% set name = "watershed-sv" %}
{% set version = "VERSION_PLACEHOLDER" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jasonbhn/Watershed-SV/archive/VERSION_PLACEHOLDER.tar.gz
  sha256: SHA256SUM_PLACEHOLDER

build:
  noarch: python
  number: BUILD_PLACEHOLDER

requirements:
  run:
    - bedtools
    - numpy >1.24
    - pandas
    - python >3.9
    - pysam
    - polars
    - pybigwig
    - pyranges
    - scipy

test:
  commands:
    - combine_all_annotations_ABC_polars -h
    - combine_all_annotations_polar -h
    - combine_roadmaps -h
    - eval_watershed_prep -h
    - extract_SV_exon_info -h
    - extract_gene_exec -h
    - extract_rare_variants -h
    - generate_annotations -h
    - generate_annotations_ABC -h
    - merge_enhancers -h
    - sv_to_gene_bw_scores -h
    - sv_to_gene_cpg -h
    - sv_to_gene_dist -h
    - train_test_predict_split_annotation -h

about:
  home: https://github.com/jasonbhn/Watershed-SV
  summary: Watershed-SV extends Watershed to model the impact of rare SVs

extra:
  recipe-maintainers:
    - danielnachun
