context:
  version: VERSION_PLACEHOLDER

package:
  name: watershed-sv
  version: ${{ version }}

source:
  url: https://github.com/jasonbhn/Watershed-SV/archive/${{ version }}.tar.gz
  sha256: SHA256SUM_PLACEHOLDER

build:
  number: BUILD_PLACEHOLDER
  noarch: python

requirements:
  run:
    - bedtools
    - numpy >1.24
    - pandas
    - python >3.9
    - pyarrow
    - pysam
    - polars
    - pybigwig
    - pyranges
    - scipy

tests:
  - script:
    - combine_all_annotations_ABC_polars -h
    - combine_all_annotations_polar -h
    - combine_roadmaps -h
    - eval_watershed_prep -h
    - extract_SV_exon_info -h
    - extract_gene_exec -h
    - extract_rare_variants -h
    - generate_annotations -h
    - generate_annotations_ABC -h
    - merge_enhancers -h
    - sv_to_gene_bw_scores -h
    - sv_to_gene_cpg -h
    - sv_to_gene_dist -h
    - train_test_predict_split_annotation -h

about:
  summary: Watershed-SV extends Watershed to model the impact of rare SVs
  homepage: https://github.com/jasonbhn/Watershed-SV

extra:
  recipe-maintainers:
    - danielnachun

