name: Build conda package

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to package
        required: true
      build:
        description: "Build revision of package (default: 0)"
        required: false
        default: '0'

jobs:
  build_package:
    name: Build conda package for noarch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_TOKEN }}
      ANACONDA_OWNER: dnachun

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create recipe from template
        run: |
          mkdir /tmp/recipe
          cp .github/recipe/meta.yaml /tmp/recipe/meta.yaml
          cp .github/recipe/build.sh /tmp/recipe/build.sh
          version=${{ github.event.inputs.version }}
          build=${{ github.event.inputs.build }}
          wget https://github.com/jasonbhn/Watershed-SV/archive/${version}.tar.gz
          sha256sum=$(sha256sum ${version}.tar.gz | cut -d ' ' -f 1)
          sed -i "s/VERSION_PLACEHOLDER/${version}/g" /tmp/recipe/meta.yaml
          sed -i "s/SHA256SUM_PLACEHOLDER/${sha256sum}/g" /tmp/recipe/meta.yaml
          sed -i "s/BUILD_PLACEHOLDER/${build}/g" /tmp/recipe/meta.yaml

      - name: Setup up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export docker containers
        uses: docker/build-push-action@v4
        with:
          load: true
          file: .github/dockerfiles/rattler-build_container.df
          tags: rattler-build:latest

      - name: Build conda packages
        run: |
          docker run --rm --volume /tmp:/tmp --volume $(pwd) --workdir $(pwd) rattler-build \
            rattler-build build -c dnachun -c conda-forge -c bioconda \
            --output-dir /tmp/rattler-build --recipe-dir /tmp/recipe

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: Upload packages
        shell: pixi exec --spec rattler-build -- bash -e {0}
        run: rattler-build upload anaconda --force /tmp/conda-bld/noarch/*.conda
