name: Build conda package

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to package
        required: true
        default: 'latest'
      build:
        description: "Build revision of package (default: 0)"
        required: false
        default: '0'

jobs:
  build_package:
    name: Build conda package for noarch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_TOKEN }}
      ANACONDA_OWNER: dnachun

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: latest-version
        name: Get latest version
        if: ${{ github.event.inputs.version }} == "latest"
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: ${{ github.repository }}

      - name: Set version
        id: set-version
        run: |
          if [[ ${{ github.event.inputs.version }} != "latest" ]]; then
            version=${{ github.event.inputs.version }}
          else
            version=${{ steps.latest-version.outputs.release }}
          fi
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: Download release
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ steps.set-version.outputs.version }}
          out-file-path: /tmp/recipe
          tarBall: true

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          run-install: false

      - name: Create recipe from template
        shell: pixi exec --spec sed --spec coreutils -- bash -e {0}
        run: |
          cp .github/recipe/build.sh /tmp/recipe/build.sh
          cp .github/recipe/recipe.yaml /tmp/recipe/recipe.yaml
          repository=${{ github.repository }}
          build=${{ github.event.inputs.build }}
          version=${{ steps.set-version.outputs.version }}
          sha256sum=$(sha256sum /tmp/recipe/${repository//*\//}-${version}.tar.gz | cut -d ' ' -f 1)
          sed -i "s/VERSION_PLACEHOLDER/${version}/g" /tmp/recipe/recipe.yaml
          sed -i "s/SHA256SUM_PLACEHOLDER/${sha256sum}/g" /tmp/recipe/recipe.yaml
          sed -i "s/BUILD_PLACEHOLDER/${build}/g" /tmp/recipe/recipe.yaml

      - name: Setup up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export docker containers
        uses: docker/build-push-action@v6
        with:
          load: true
          file: .github/dockerfiles/rattler-build_container.df
          tags: rattler-build:latest

      - name: Build conda packages
        run: |
          docker run --rm --volume /tmp:/tmp --volume $(pwd) --workdir $(pwd) rattler-build \
            rattler-build build -c dnachun -c conda-forge -c bioconda \
            --output-dir /tmp/rattler-build --recipe-dir /tmp/recipe

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: Upload packages
        shell: pixi exec --spec rattler-build -- bash -e {0}
        run: rattler-build upload anaconda --force /tmp/rattler-build/noarch/*.conda
