name: Dispatch push containers to registries

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to install into container
        required: true

jobs:
  push_docker_containers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ghcr.io with docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to quay.io with docker
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ vars.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}

      - name: Log in to docker.io with docker
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ vars.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_TOKEN }}

      - name: Build and push docker containers
        uses: docker/build-push-action@v4
        with:
          build-args: VERSION=${{ github.event.inputs.version }}
          file: .github/dockerfiles/pixi_watershed.df
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/watershed-sv:${{ github.events.input.version }}
            quay.io/${{ vars.QUAYIO_USERNAME }}/watershed-sv:${{ github.events.input.version }}
            docker.io/${{ vars.DOCKERIO_USERNAME }}/watershed-sv:${{ github.events.input.version }}
